USE brewery_pms;

INSERT INTO production_metrics (
  `date`,
  `target_date`,
  `entry_type`,
  `production_productivity_ftd_actual`,
  `production_productivity_ftd_target`,
  `production_productivity_mtd_actual`,
  `production_productivity_mtd_target`,
  `production_productivity_ytd_actual`,
  `production_productivity_ytd_target`,
  `logistics_productivity_ftd_actual`,
  `logistics_productivity_ftd_target`,
  `logistics_productivity_mtd_actual`,
  `logistics_productivity_mtd_target`,
  `logistics_productivity_ytd_actual`,
  `logistics_productivity_ytd_target`,
  `kpi_sensory_score_ftd_actual`,
  `kpi_sensory_score_ftd_target`,
  `kpi_sensory_score_mtd_actual`,
  `kpi_sensory_score_mtd_target`,
  `kpi_sensory_score_ytd_actual`,
  `kpi_sensory_score_ytd_target`,
  `kpi__consumer_complaint_units_/_mhl_ftd_actual`,
  `kpi__consumer_complaint__units_/_mhl_ftd_target`,
  `kpi_consumer_complaint_units_mhl_mtd_actual`,
  `kpi_consumer_complaint_units_mhl_mtd_target`,
  `kpi_consumer_complaint_units_mhl_ytd_actual`,
  `kpi_consumer_complaint_units_mhl_ytd_target`,
  `kpi__customer_complaint__units_/_mhl_ftd_actual`,
  `kpi__customer_complaint__units_/_mhl_ftd_target`,
  `kpi_customer_complaint_units_mhl_mtd_actual`,
  `kpi_customer_complaint_units_mhl_mtd_target`,
  `kpi_customer_complaint_units_mhl_ytd_actual`,
  `kpi_customer_complaint_units_mhl_ytd_target`,
  `no_of_brews_ftd_actual`,
  `no_of_brews_ftd_target`,
  `no_of_brews_mtd_actual`,
  `no_of_brews_mtd_target`,
  `no_of_brews_ytd_actual`,
  `no_of_brews_ytd_target`,
  `dispatch_ftd_actual`,
  `dispatch_ftd_target`,
  `dispatch_mtd_actual`,
  `dispatch_mtd_target`,
  `dispatch_ytd_actual`,
  `dispatch_ytd_target`,
  `process_confirmation_b&p_ftd_actual`,
  `process_confirmation_b&p_ftd_target`,
  `process_confirmation_bp_mtd_actual`,
  `process_confirmation_bp_mtd_target`,
  `process_confirmation_bp_ytd_actual`,
  `process_confirmation_bp_ytd_target`,
  `process_confirmation_pack_ftd_actual`,
  `process_confirmation_pack_ftd_target`,
  `process_confirmation_pack_mtd_actual`,
  `process_confirmation_pack_mtd_target`,
  `process_confirmation_pack_ytd_actual`,
  `process_confirmation_pack_ytd_target`,
  `kpi__oee__ftd_actual`,
  `kpi__oee__ftd_target`,
  `kpi__oee__mtd_actual`,
  `kpi__oee__mtd_target`,
  `kpi_oee_ytd_actual`,
  `kpi_oee_ytd_target`,
  `kpi__beer_loss__ftd_actual`,
  `kpi__beer_loss__ftd_target`,
  `kpi__beer_loss__mtd_actual`,
  `kpi__beer_loss__mtd_target`,
  `kpi_beer_loss_ytd_actual`,
  `kpi_beer_loss_ytd_target`,
  `kpi__wur_hl/hl_ftd_actual`,
  `kpi__wur_hl/hl_ftd_target`,
  `kpi__wur_hl/hl_mtd_actual`,
  `kpi__wur_hl/hl_mtd_target`,
  `kpi_wur_hlhl_ytd_actual`,
  `kpi_wur_hlhl_ytd_target`,
  `kpi__electricity_kwh/hl_ftd_actual`,
  `kpi__electricity_kwh/hl_ftd_target`,
  `kpi__electricity_kwh/hl_mtd_actual`,
  `kpi__electricity_kwh/hl_mtd_target`,
  `kpi_electricity_kwh_hl_ytd_actual`,
  `kpi_electricity_kwh_hl_ytd_target`,
  `kpi__energy_kwh/hl_ftd_actual`,
  `kpi__energy_kwh/hl_ftd_target`,
  `kpi__energy_kwh/hl_mtd_actual`,
  `kpi__energy_kwh/hl_mtd_target`,
  `kpi_energy_kwh_hl_ytd_actual`,
  `kpi_energy_kwh_hl_ytd_target`,
  `kpi__rgb_ratio__ftd_actual`,
  `kpi__rgb_ratio__ftd_target`,
  `kpi__rgb_ratio__mtd_actual`,
  `kpi__rgb_ratio__mtd_target`,
  `kpi_rgb_ratio_ytd_actual`,
  `kpi_rgb_ratio_ytd_target`,
  `created_at`,
  `updated_at`
) VALUES (
  '2026-08-14 00:00:00',
  '2026-08-15 00:00:00',
  NULL,
  '4','9','7','9','8','9',
  '6','7','78','8','9','9',
  '92','95','94','95','96','95',
  '0.08','0.10','0.09','0.10','0.07','0.10',
  '0.12','0.15','0.11','0.15','0.10','0.15',
  '5','5','68','70','820','900',
  '24500','25000','315000','320000','4200000','4300000',
  '86','90','88','90','91','90',
  '84','90','87','90','90','90',
  '78','80','79','80','82','80',
  '3.8','4.0','3.6','4.0','3.4','4.0',
  '3.2','3.0','3.1','3.0','2.9','3.0',
  '8.5','8.0','8.3','8.0','8.1','8.0',
  '11.2','11.0','10.8','11.0','10.5','11.0',
  '72','75','74','75','76','75',
  NOW(),
  NOW()
)
ON DUPLICATE KEY UPDATE
  `target_date` = VALUES(`target_date`),
  `entry_type` = VALUES(`entry_type`),
  `production_productivity_ftd_actual` = VALUES(`production_productivity_ftd_actual`),
  `production_productivity_ftd_target` = VALUES(`production_productivity_ftd_target`),
  `production_productivity_mtd_actual` = VALUES(`production_productivity_mtd_actual`),
  `production_productivity_mtd_target` = VALUES(`production_productivity_mtd_target`),
  `production_productivity_ytd_actual` = VALUES(`production_productivity_ytd_actual`),
  `production_productivity_ytd_target` = VALUES(`production_productivity_ytd_target`),
  `logistics_productivity_ftd_actual` = VALUES(`logistics_productivity_ftd_actual`),
  `logistics_productivity_ftd_target` = VALUES(`logistics_productivity_ftd_target`),
  `logistics_productivity_mtd_actual` = VALUES(`logistics_productivity_mtd_actual`),
  `logistics_productivity_mtd_target` = VALUES(`logistics_productivity_mtd_target`),
  `logistics_productivity_ytd_actual` = VALUES(`logistics_productivity_ytd_actual`),
  `logistics_productivity_ytd_target` = VALUES(`logistics_productivity_ytd_target`),
  `kpi_sensory_score_ftd_actual` = VALUES(`kpi_sensory_score_ftd_actual`),
  `kpi_sensory_score_ftd_target` = VALUES(`kpi_sensory_score_ftd_target`),
  `kpi_sensory_score_mtd_actual` = VALUES(`kpi_sensory_score_mtd_actual`),
  `kpi_sensory_score_mtd_target` = VALUES(`kpi_sensory_score_mtd_target`),
  `kpi_sensory_score_ytd_actual` = VALUES(`kpi_sensory_score_ytd_actual`),
  `kpi_sensory_score_ytd_target` = VALUES(`kpi_sensory_score_ytd_target`),
  `kpi__consumer_complaint_units_/_mhl_ftd_actual` = VALUES(`kpi__consumer_complaint_units_/_mhl_ftd_actual`),
  `kpi__consumer_complaint__units_/_mhl_ftd_target` = VALUES(`kpi__consumer_complaint__units_/_mhl_ftd_target`),
  `kpi_consumer_complaint_units_mhl_mtd_actual` = VALUES(`kpi_consumer_complaint_units_mhl_mtd_actual`),
  `kpi_consumer_complaint_units_mhl_mtd_target` = VALUES(`kpi_consumer_complaint_units_mhl_mtd_target`),
  `kpi_consumer_complaint_units_mhl_ytd_actual` = VALUES(`kpi_consumer_complaint_units_mhl_ytd_actual`),
  `kpi_consumer_complaint_units_mhl_ytd_target` = VALUES(`kpi_consumer_complaint_units_mhl_ytd_target`),
  `kpi__customer_complaint__units_/_mhl_ftd_actual` = VALUES(`kpi__customer_complaint__units_/_mhl_ftd_actual`),
  `kpi__customer_complaint__units_/_mhl_ftd_target` = VALUES(`kpi__customer_complaint__units_/_mhl_ftd_target`),
  `kpi_customer_complaint_units_mhl_mtd_actual` = VALUES(`kpi_customer_complaint_units_mhl_mtd_actual`),
  `kpi_customer_complaint_units_mhl_mtd_target` = VALUES(`kpi_customer_complaint_units_mhl_mtd_target`),
  `kpi_customer_complaint_units_mhl_ytd_actual` = VALUES(`kpi_customer_complaint_units_mhl_ytd_actual`),
  `kpi_customer_complaint_units_mhl_ytd_target` = VALUES(`kpi_customer_complaint_units_mhl_ytd_target`),
  `no_of_brews_ftd_actual` = VALUES(`no_of_brews_ftd_actual`),
  `no_of_brews_ftd_target` = VALUES(`no_of_brews_ftd_target`),
  `no_of_brews_mtd_actual` = VALUES(`no_of_brews_mtd_actual`),
  `no_of_brews_mtd_target` = VALUES(`no_of_brews_mtd_target`),
  `no_of_brews_ytd_actual` = VALUES(`no_of_brews_ytd_actual`),
  `no_of_brews_ytd_target` = VALUES(`no_of_brews_ytd_target`),
  `dispatch_ftd_actual` = VALUES(`dispatch_ftd_actual`),
  `dispatch_ftd_target` = VALUES(`dispatch_ftd_target`),
  `dispatch_mtd_actual` = VALUES(`dispatch_mtd_actual`),
  `dispatch_mtd_target` = VALUES(`dispatch_mtd_target`),
  `dispatch_ytd_actual` = VALUES(`dispatch_ytd_actual`),
  `dispatch_ytd_target` = VALUES(`dispatch_ytd_target`),
  `process_confirmation_b&p_ftd_actual` = VALUES(`process_confirmation_b&p_ftd_actual`),
  `process_confirmation_b&p_ftd_target` = VALUES(`process_confirmation_b&p_ftd_target`),
  `process_confirmation_bp_mtd_actual` = VALUES(`process_confirmation_bp_mtd_actual`),
  `process_confirmation_bp_mtd_target` = VALUES(`process_confirmation_bp_mtd_target`),
  `process_confirmation_bp_ytd_actual` = VALUES(`process_confirmation_bp_ytd_actual`),
  `process_confirmation_bp_ytd_target` = VALUES(`process_confirmation_bp_ytd_target`),
  `process_confirmation_pack_ftd_actual` = VALUES(`process_confirmation_pack_ftd_actual`),
  `process_confirmation_pack_ftd_target` = VALUES(`process_confirmation_pack_ftd_target`),
  `process_confirmation_pack_mtd_actual` = VALUES(`process_confirmation_pack_mtd_actual`),
  `process_confirmation_pack_mtd_target` = VALUES(`process_confirmation_pack_mtd_target`),
  `process_confirmation_pack_ytd_actual` = VALUES(`process_confirmation_pack_ytd_actual`),
  `process_confirmation_pack_ytd_target` = VALUES(`process_confirmation_pack_ytd_target`),
  `kpi__oee__ftd_actual` = VALUES(`kpi__oee__ftd_actual`),
  `kpi__oee__ftd_target` = VALUES(`kpi__oee__ftd_target`),
  `kpi__oee__mtd_actual` = VALUES(`kpi__oee__mtd_actual`),
  `kpi__oee__mtd_target` = VALUES(`kpi__oee__mtd_target`),
  `kpi_oee_ytd_actual` = VALUES(`kpi_oee_ytd_actual`),
  `kpi_oee_ytd_target` = VALUES(`kpi_oee_ytd_target`),
  `kpi__beer_loss__ftd_actual` = VALUES(`kpi__beer_loss__ftd_actual`),
  `kpi__beer_loss__ftd_target` = VALUES(`kpi__beer_loss__ftd_target`),
  `kpi__beer_loss__mtd_actual` = VALUES(`kpi__beer_loss__mtd_actual`),
  `kpi__beer_loss__mtd_target` = VALUES(`kpi__beer_loss__mtd_target`),
  `kpi_beer_loss_ytd_actual` = VALUES(`kpi_beer_loss_ytd_actual`),
  `kpi_beer_loss_ytd_target` = VALUES(`kpi_beer_loss_ytd_target`),
  `kpi__wur_hl/hl_ftd_actual` = VALUES(`kpi__wur_hl/hl_ftd_actual`),
  `kpi__wur_hl/hl_ftd_target` = VALUES(`kpi__wur_hl/hl_ftd_target`),
  `kpi__wur_hl/hl_mtd_actual` = VALUES(`kpi__wur_hl/hl_mtd_actual`),
  `kpi__wur_hl/hl_mtd_target` = VALUES(`kpi__wur_hl/hl_mtd_target`),
  `kpi_wur_hlhl_ytd_actual` = VALUES(`kpi_wur_hlhl_ytd_actual`),
  `kpi_wur_hlhl_ytd_target` = VALUES(`kpi_wur_hlhl_ytd_target`),
  `kpi__electricity_kwh/hl_ftd_actual` = VALUES(`kpi__electricity_kwh/hl_ftd_actual`),
  `kpi__electricity_kwh/hl_ftd_target` = VALUES(`kpi__electricity_kwh/hl_ftd_target`),
  `kpi__electricity_kwh/hl_mtd_actual` = VALUES(`kpi__electricity_kwh/hl_mtd_actual`),
  `kpi__electricity_kwh/hl_mtd_target` = VALUES(`kpi__electricity_kwh/hl_mtd_target`),
  `kpi_electricity_kwh_hl_ytd_actual` = VALUES(`kpi_electricity_kwh_hl_ytd_actual`),
  `kpi_electricity_kwh_hl_ytd_target` = VALUES(`kpi_electricity_kwh_hl_ytd_target`),
  `kpi__energy_kwh/hl_ftd_actual` = VALUES(`kpi__energy_kwh/hl_ftd_actual`),
  `kpi__energy_kwh/hl_ftd_target` = VALUES(`kpi__energy_kwh/hl_ftd_target`),
  `kpi__energy_kwh/hl_mtd_actual` = VALUES(`kpi__energy_kwh/hl_mtd_actual`),
  `kpi__energy_kwh/hl_mtd_target` = VALUES(`kpi__energy_kwh/hl_mtd_target`),
  `kpi_energy_kwh_hl_ytd_actual` = VALUES(`kpi_energy_kwh_hl_ytd_actual`),
  `kpi_energy_kwh_hl_ytd_target` = VALUES(`kpi_energy_kwh_hl_ytd_target`),
  `kpi__rgb_ratio__ftd_actual` = VALUES(`kpi__rgb_ratio__ftd_actual`),
  `kpi__rgb_ratio__ftd_target` = VALUES(`kpi__rgb_ratio__ftd_target`),
  `kpi__rgb_ratio__mtd_actual` = VALUES(`kpi__rgb_ratio__mtd_actual`),
  `kpi__rgb_ratio__mtd_target` = VALUES(`kpi__rgb_ratio__mtd_target`),
  `kpi_rgb_ratio_ytd_actual` = VALUES(`kpi_rgb_ratio_ytd_actual`),
  `kpi_rgb_ratio_ytd_target` = VALUES(`kpi_rgb_ratio_ytd_target`),
  `updated_at` = NOW();

SELECT *
FROM production_metrics
WHERE `date` = '2026-08-14 00:00:00';
