spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  shutdown: graceful

logging:
  level:
    root: WARN
    org.springframework.web: INFO